export const dummyTemuan = [
    {
        id: 11,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-12",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Proses",
    },
    {
        id: 12,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-12",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Tunda",
    },
    {
        id: 13,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-24",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Tunda",
    },
    {
        id: 14,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-24",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Tunda",
    },
    {
        id: 15,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-26",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Proses",
    },
    {
        id: 16,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-26",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Selesai",
    },
    {
        id: 17,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-26",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Proses",
    },
    {
        id: 18,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-27",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Selesai",
    },
    {
        id: 19,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-28",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Proses",
    },
    {
        id: 20,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-28",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Selesai",
    },
        {
        id: 21,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-11-28",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Selesai",
    },
    {
        id: 22,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-12-02",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Selesai",
    },
    {
        id: 23,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-12-02",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Selesai",
    },
    {
        id: 24,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-12-02",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Proses",
    },
    {
        id: 25,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-12-04",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Tunda",
    },
        {
        id: 26,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-12-04",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Proses",
    },
    {
        id: 27,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-12-04",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Tunda",
    },
    {
        id: 28,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-12-06",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Tunda",
    },
    {
        id: 29,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-12-06",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Draf",
    },
    {
        id: 30,
        finding: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        date: "2025-12-09",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Tunda",
    },
        {
        id: 31,
        finding: "Kabel listrik belakang commshop belum terisolasi dengan baik, bisa menyebabkan korsleting jika terkena air hujan. Mohon segera ditindaklanjuti untuk menghindari potensi bahaya kebakaran.",
        date: "2025-12-10",
        name: "Firdaus",
        division: "ICT",
        to_division: "Electric",
        status: "Draf",
    },
    {
        id: 32,
        finding: "Landing boading di sisi utara rusak dan berbahaya bagi pengguna tangga. Harap segera diperbaiki untuk mencegah kecelakaan.",
        date: "2025-12-10",
        name: "Isharyanto",
        division: "ICT",
        to_division: "Facility",
        status: "Draf",
    },
    {
        id: 33,
        finding: "cctv main office mati sejak kemarin, tolong dicek dan diperbaiki segera. Ini penting untuk keamanan gedung.",
        date: "2025-12-11",
        name: "Kasah",
        division: "Camp",
        to_division: "ICT",
        status: "Tunda",
    },
    {
        id: 34,
        finding: "ada lobang bekas pipa bocor di plafon ruang server, khawatir akan membahayakan peralatan IT. Mohon segera diperbaiki.",
        date: "2025-12-11",
        name: "Firman",
        division: "ICT",
        to_division: "Camp",
        status: "Tunda",
    },
    {
        id: 35,
        finding: "Kebocoran pipa air di kamar b2 perlu segera diperbaiki untuk mencegah kerusakan lebih lanjut pada struktur bangunan.",
        date: "2025-12-11",
        name: "Icav",
        division: "ICT",
        to_division: "Camp",
        status: "Proses",
    },
    {
        id: 36,
        finding: "pintu otomatis dimain office sering macet, tolong dicek dan diperbaiki agar berfungsi normal kembali. sudah rusak sejak minggu lalu.",
        date: "2025-12-12",
        name: "Mahfud",
        division: "DCRM",
        to_division: "ICT",
        status: "Tunda",
    },
    {
        id: 37,
        finding: "Tiang listrik di parkiran belakang miring, berbahaya bagi kendaraan yang parkir di sekitarnya. Mohon segera diperbaiki.",
        date: "2025-12-12",
        name: "Adnan",
        division: "Security",
        to_division: "Facility",
        status: "Proses",
    },
    {
        id: 38,
        finding: "ada tumpukan berkas file lama di ruang arsip yang sudah tidak terpakai, tolong segera dibersihkan untuk menghindari risiko kebakaran.",
        date: "2025-12-14",
        name: "Kasah",
        division: "Camp",
        to_division: "DCRM",
        status: "Proses",
    },
    {
        id: 39,
        finding: "Dahan pohon besar di halaman depan retak dan berpotensi tumbang. Harap segera dipotong untuk mencegah bahaya bagi pengunjung.",
        date: "2025-12-14",
        name: "Suhendri",
        division: "ICT",
        to_division: "Camp",
        status: "Selesai",
    },
    {
        id: 40,
        finding: "Tangga naik ke portacamp coman rusak dan berbahaya untuk digunakan. Mohon segera diperbaiki agar aman bagi karyawan.",
        date: "2025-12-15",
        name: "Firdaus",
        division: "ICT",
        to_division: "BEP",
        status: "Selesai",
    },

]

export const dummyPersonil = [
  { id: 1, nama: "Firman",      divisi: "ICT",           skor: 100 },
  { id: 2, nama: "Isharyanto",  divisi: "ICT",           skor: 97 },
  { id: 3, nama: "Firdaus",     divisi: "ICT to Electric", skor: 91 },
  { id: 4, nama: "Arif",        divisi: "Facility",      skor: 88 },
  { id: 5, nama: "Budi",        divisi: "Security",      skor: 80 },
  { id: 6, nama: "Joko",        divisi: "Produksi",      skor: 75 },
  // ...lanjutkan sesuai kebutuhan
]